// Code generated by go-swagger; DO NOT EDIT.

package lm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"
	// "crypto/tls"
	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/logicmonitor/lm-sdk-go/models"
)

// NewAddLmotelCollectorParams creates a new AddLmotelCollectorParams object
// with the default values initialized.
func NewAddLmotelCollectorParams() *AddLmotelCollectorParams {
	var ()
	/*
	transport := http.DefaultTransport.(*http.Transport).Clone()
    transport.TLSClientConfig = &tls.Config{InsecureSkipVerify: true, MinVersion: tls.VersionTLS12}
    clientTransport := (http.RoundTripper)(transport)
	httpClient := &http.Client{Transport: clientTransport, Timeout: 0}
	*/
	return &AddLmotelCollectorParams{
		// HTTPClient: httpClient,
		timeout: cr.DefaultTimeout,
	}
}

// NewAddLmotelCollectorParamsWithTimeout creates a new AddLmotelCollectorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddLmotelCollectorParamsWithTimeout(timeout time.Duration) *AddLmotelCollectorParams {
	var ()
	return &AddLmotelCollectorParams{

		timeout: timeout,
	}
}

// NewAddLmotelCollectorParamsWithContext creates a new AddLmotelCollectorParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddLmotelCollectorParamsWithContext(ctx context.Context) *AddLmotelCollectorParams {
	var ()
	return &AddLmotelCollectorParams{

		Context: ctx,
	}
}

// NewAddLmotelCollectorParamsWithHTTPClient creates a new AddLmotelCollectorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddLmotelCollectorParamsWithHTTPClient(client *http.Client) *AddLmotelCollectorParams {
	var ()
	return &AddLmotelCollectorParams{
		HTTPClient: client,
	}
}

/*AddLmotelCollectorParams contains all the parameters to send to the API endpoint
for the add collector operation typically these are written to a http.Request
*/
type AddLmotelCollectorParams struct {

	/*Body*/
	Body *models.LmotelCollector

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add collector params
func (o *AddLmotelCollectorParams) WithTimeout(timeout time.Duration) *AddLmotelCollectorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add collector params
func (o *AddLmotelCollectorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add collector params
func (o *AddLmotelCollectorParams) WithContext(ctx context.Context) *AddLmotelCollectorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add collector params
func (o *AddLmotelCollectorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add collector params
func (o *AddLmotelCollectorParams) WithHTTPClient(client *http.Client) *AddLmotelCollectorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add collector params
func (o *AddLmotelCollectorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add collector params
func (o *AddLmotelCollectorParams) WithBody(body *models.LmotelCollector) *AddLmotelCollectorParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add collector params
func (o *AddLmotelCollectorParams) SetBody(body *models.LmotelCollector) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AddLmotelCollectorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
