// Code generated by go-swagger; DO NOT EDIT.

package lm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"
	// "crypto/tls"
	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteCollectorByIDParams creates a new DeleteCollectorByIDParams object
// with the default values initialized.
func NewDeleteLmotelCollectorByIDParams() *DeleteLmotelCollectorByIDParams {
	var ()
	// Added to Skip SSL verification
	// transport := http.DefaultTransport.(*http.Transport).Clone()
	// transport.TLSClientConfig = &tls.Config{InsecureSkipVerify: true, MinVersion: tls.VersionTLS12}
	// clientTransport := (http.RoundTripper)(transport)
	// httpClient := &http.Client{Transport: clientTransport, Timeout: 0}
	// Added to Skip SSL verification
	return &DeleteLmotelCollectorByIDParams{
		// HTTPClient: httpClient, // Added
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCollectorByIDParamsWithTimeout creates a new DeleteCollectorByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteLmotelCollectorByIDParamsWithTimeout(timeout time.Duration) *DeleteLmotelCollectorByIDParams {
	var ()
	return &DeleteLmotelCollectorByIDParams{

		timeout: timeout,
	}
}

// NewDeleteCollectorByIDParamsWithContext creates a new DeleteCollectorByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteLmotelCollectorByIDParamsWithContext(ctx context.Context) *DeleteLmotelCollectorByIDParams {
	var ()
	return &DeleteLmotelCollectorByIDParams{

		Context: ctx,
	}
}

// NewDeleteCollectorByIDParamsWithHTTPClient creates a new DeleteCollectorByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteLmotelCollectorByIDParamsWithHTTPClient(client *http.Client) *DeleteLmotelCollectorByIDParams {
	var ()
	return &DeleteLmotelCollectorByIDParams{
		HTTPClient: client,
	}
}

/*DeleteCollectorByIDParams contains all the parameters to send to the API endpoint
for the delete collector by Id operation typically these are written to a http.Request
*/
type DeleteLmotelCollectorByIDParams struct {

	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete collector by Id params
func (o *DeleteLmotelCollectorByIDParams) WithTimeout(timeout time.Duration) *DeleteLmotelCollectorByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete collector by Id params
func (o *DeleteLmotelCollectorByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete collector by Id params
func (o *DeleteLmotelCollectorByIDParams) WithContext(ctx context.Context) *DeleteLmotelCollectorByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete collector by Id params
func (o *DeleteLmotelCollectorByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete collector by Id params
func (o *DeleteLmotelCollectorByIDParams) WithHTTPClient(client *http.Client) *DeleteLmotelCollectorByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete collector by Id params
func (o *DeleteLmotelCollectorByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete collector by Id params
func (o *DeleteLmotelCollectorByIDParams) WithID(id int32) *DeleteLmotelCollectorByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete collector by Id params
func (o *DeleteLmotelCollectorByIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteLmotelCollectorByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
