// Code generated by go-swagger; DO NOT EDIT.

package lm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"
	// "crypto/tls"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCollectorByIDParams creates a new GetCollectorByIDParams object
// with the default values initialized.
func NewGetLmotelCollectorByIDParams() *GetLmotelCollectorByIDParams {
	var ()
	return &GetLmotelCollectorByIDParams{
		Headers: http.Header{"X-version": []string{"4"}},
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCollectorByIDParamsWithTimeout creates a new GetCollectorByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLmotelCollectorByIDParamsWithTimeout(timeout time.Duration) *GetLmotelCollectorByIDParams {
	var ()
	return &GetLmotelCollectorByIDParams{

		timeout: timeout,
	}
}

// NewGetCollectorByIDParamsWithContext creates a new GetCollectorByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLmotelCollectorByIDParamsWithContext(ctx context.Context) *GetLmotelCollectorByIDParams {
	var ()
	return &GetLmotelCollectorByIDParams{

		Context: ctx,
	}
}

// NewGetCollectorByIDParamsWithHTTPClient creates a new GetCollectorByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLmotelCollectorByIDParamsWithHTTPClient(client *http.Client) *GetLmotelCollectorByIDParams {
	var ()
	return &GetLmotelCollectorByIDParams{
		HTTPClient: client,
	}
}

/*GetCollectorByIDParams contains all the parameters to send to the API endpoint
for the get collector by Id operation typically these are written to a http.Request
*/
type GetLmotelCollectorByIDParams struct {

	Headers    http.Header
	/*Fields*/
	Fields *string
	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get collector by Id params
func (o *GetLmotelCollectorByIDParams) WithTimeout(timeout time.Duration) *GetLmotelCollectorByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get collector by Id params
func (o *GetLmotelCollectorByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get collector by Id params
func (o *GetLmotelCollectorByIDParams) WithContext(ctx context.Context) *GetLmotelCollectorByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get collector by Id params
func (o *GetLmotelCollectorByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get collector by Id params
func (o *GetLmotelCollectorByIDParams) WithHTTPClient(client *http.Client) *GetLmotelCollectorByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get collector by Id params
func (o *GetLmotelCollectorByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the get collector by Id params
func (o *GetLmotelCollectorByIDParams) WithFields(fields *string) *GetLmotelCollectorByIDParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the get collector by Id params
func (o *GetLmotelCollectorByIDParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithID adds the id to the get collector by Id params
func (o *GetLmotelCollectorByIDParams) WithID(id int32) *GetLmotelCollectorByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get collector by Id params
func (o *GetLmotelCollectorByIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetLmotelCollectorByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}
	for header, value := range o.Headers {
        r.SetHeaderParam(header, value...)
    }
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
