// Code generated by go-swagger; DO NOT EDIT.

package lm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"log"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/logicmonitor/lm-sdk-go/models"
)

// GetCollectorByIDReader is a Reader for the GetCollectorByID structure.
type GetLmotelCollectorByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLmotelCollectorByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {

	switch response.Code() {

	case 200:
		result := NewGetLmotelCollectorByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetLmotelCollectorByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetCollectorByIDOK creates a GetCollectorByIDOK with default headers values
func NewGetLmotelCollectorByIDOK() *GetLmotelCollectorByIDOK {
	return &GetLmotelCollectorByIDOK{}
}

/*GetCollectorByIDOK handles this case with default header values.

successful operation
*/
type GetLmotelCollectorByIDOK struct {
	Payload *models.LmotelCollectorData
}

func (o *GetLmotelCollectorByIDOK) Error() string {
	return fmt.Sprintf("[GET /setting/collectors/{id}][%d] getLmotelCollectorByIdOK  %+v", 200, o.Payload)
}

func (o *GetLmotelCollectorByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LmotelCollectorData)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}
	log.Println(o.Payload)

	return nil
}

// NewGetCollectorByIDDefault creates a GetCollectorByIDDefault with default headers values
func NewGetLmotelCollectorByIDDefault(code int) *GetLmotelCollectorByIDDefault {
	return &GetLmotelCollectorByIDDefault{
		_statusCode: code,
	}
}

/*GetCollectorByIDDefault handles this case with default header values.

Error
*/
type GetLmotelCollectorByIDDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the get collector by Id default response
func (o *GetLmotelCollectorByIDDefault) Code() int {
	return o._statusCode
}

func (o *GetLmotelCollectorByIDDefault) Error() string {
	return fmt.Sprintf("[GET /setting/collectors/{id}][%d] getLmotelCollectorById default  %+v", o._statusCode, o.Payload)
}

func (o *GetLmotelCollectorByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
