// Code generated by go-swagger; DO NOT EDIT.

package lm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/logicmonitor/lm-sdk-go/models"
)

// UpdateCollectorByIDReader is a Reader for the UpdateCollectorByID structure.
type UpdateLmotelCollectorByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateLmotelCollectorByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateLmotelCollectorByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewUpdateLmotelCollectorByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateCollectorByIDOK creates a UpdateCollectorByIDOK with default headers values
func NewUpdateLmotelCollectorByIDOK() *UpdateLmotelCollectorByIDOK {
	return &UpdateLmotelCollectorByIDOK{}
}

/*UpdateCollectorByIDOK handles this case with default header values.

successful operation
*/
type UpdateLmotelCollectorByIDOK struct {
	Payload *models.LmotelCollector
}

func (o *UpdateLmotelCollectorByIDOK) Error() string {
	return fmt.Sprintf("[PUT /setting/collectors/collector/{id}][%d] updateCollectorByIdOK  %+v", 200, o.Payload)
}

func (o *UpdateLmotelCollectorByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LmotelCollector) // Need to conform LmotelCollectorData or LmotelCollector

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateCollectorByIDDefault creates a UpdateCollectorByIDDefault with default headers values
func NewUpdateLmotelCollectorByIDDefault(code int) *UpdateLmotelCollectorByIDDefault {
	return &UpdateLmotelCollectorByIDDefault{
		_statusCode: code,
	}
}

/*UpdateCollectorByIDDefault handles this case with default header values.

Error
*/
type UpdateLmotelCollectorByIDDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the update collector by Id default response
func (o *UpdateLmotelCollectorByIDDefault) Code() int {
	return o._statusCode
}

func (o *UpdateLmotelCollectorByIDDefault) Error() string {
	return fmt.Sprintf("[PUT /setting/collectors/collector/{id}][%d] updateLmotelCollectorById default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateLmotelCollectorByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
