// Code generated by go-swagger; DO NOT EDIT.

package lm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"
	"crypto/tls"
	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/logicmonitor/lm-sdk-go/models"
)


// NewUpdateCollectorByIDParams creates a new UpdateCollectorByIDParams object
// with the default values initialized.
func NewUpdateLmotelCollectorByIDParams() *UpdateLmotelCollectorByIDParams {
	var (
		LmotelcollectorLoadBalancedDefault	= bool(false)
		forceUpdateFailedOverDevicesDefault	= bool(false)
	)
	// Added to Skip SSL verification
	transport := http.DefaultTransport.(*http.Transport).Clone()
	transport.TLSClientConfig = &tls.Config{InsecureSkipVerify: true, MinVersion: tls.VersionTLS12}
	clientTransport := (http.RoundTripper)(transport)
	httpClient := &http.Client{Transport: clientTransport, Timeout: 0}
	// Added to Skip SSL verification

	return &UpdateLmotelCollectorByIDParams{
		LmotelCollectorLoadBalanced:        &LmotelcollectorLoadBalancedDefault,
		ForceUpdateFailedOverDevices: &forceUpdateFailedOverDevicesDefault,

		HTTPClient: httpClient, // Added
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateCollectorByIDParamsWithTimeout creates a new UpdateCollectorByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateLmotelCollectorByIDParamsWithTimeout(timeout time.Duration) *UpdateLmotelCollectorByIDParams {
	var (
		LmotelcollectorLoadBalancedDefault	= bool(false)
		forceUpdateFailedOverDevicesDefault = bool(false)
	)
	return &UpdateLmotelCollectorByIDParams{
		LmotelCollectorLoadBalanced:        &LmotelcollectorLoadBalancedDefault,
		ForceUpdateFailedOverDevices: &forceUpdateFailedOverDevicesDefault,

		timeout: timeout,
	}
}

// NewUpdateCollectorByIDParamsWithContext creates a new UpdateCollectorByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateLmotelCollectorByIDParamsWithContext(ctx context.Context) *UpdateLmotelCollectorByIDParams {
	var (
		LmotelcollectorLoadBalancedDefault	= bool(false)
		forceUpdateFailedOverDevicesDefault = bool(false)
	)
	return &UpdateLmotelCollectorByIDParams{
		LmotelCollectorLoadBalanced:        &LmotelcollectorLoadBalancedDefault,
		ForceUpdateFailedOverDevices: &forceUpdateFailedOverDevicesDefault,

		Context: ctx,
	}
}

// NewUpdateCollectorByIDParamsWithHTTPClient creates a new UpdateCollectorByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateLmotelCollectorByIDParamsWithHTTPClient(client *http.Client) *UpdateLmotelCollectorByIDParams {
	var (
		LmotelcollectorLoadBalancedDefault	= bool(false)
		forceUpdateFailedOverDevicesDefault = bool(false)
	)
	return &UpdateLmotelCollectorByIDParams{
		LmotelCollectorLoadBalanced:        &LmotelcollectorLoadBalancedDefault,
		ForceUpdateFailedOverDevices: &forceUpdateFailedOverDevicesDefault,
		HTTPClient:                   client,
	}
}

/*UpdateCollectorByIDParams contains all the parameters to send to the API endpoint
for the update collector by Id operation typically these are written to a http.Request
*/
type UpdateLmotelCollectorByIDParams struct {

	/*Body*/
	Body *models.LmotelCollector
	/*CollectorLoadBalanced*/
	LmotelCollectorLoadBalanced *bool
	/*ForceUpdateFailedOverDevices*/
	ForceUpdateFailedOverDevices *bool
	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update collector by Id params
func (o *UpdateLmotelCollectorByIDParams) WithTimeout(timeout time.Duration) *UpdateLmotelCollectorByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update collector by Id params
func (o *UpdateLmotelCollectorByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update collector by Id params
func (o *UpdateLmotelCollectorByIDParams) WithContext(ctx context.Context) *UpdateLmotelCollectorByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update collector by Id params
func (o *UpdateLmotelCollectorByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update collector by Id params
func (o *UpdateLmotelCollectorByIDParams) WithHTTPClient(client *http.Client) *UpdateLmotelCollectorByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update collector by Id params
func (o *UpdateLmotelCollectorByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update collector by Id params
func (o *UpdateLmotelCollectorByIDParams) WithBody(body *models.LmotelCollector) *UpdateLmotelCollectorByIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update collector by Id params
func (o *UpdateLmotelCollectorByIDParams) SetBody(body *models.LmotelCollector) {
	o.Body = body
}

// WithCollectorLoadBalanced adds the collectorLoadBalanced to the update collector by Id params
func (o *UpdateLmotelCollectorByIDParams) WithLmotelCollectorLoadBalanced(LmotelcollectorLoadBalanced *bool) *UpdateLmotelCollectorByIDParams {
	o.SetLmotelCollectorLoadBalanced(LmotelcollectorLoadBalanced)
	return o
}

// SetCollectorLoadBalanced adds the collectorLoadBalanced to the update collector by Id params
func (o *UpdateLmotelCollectorByIDParams) SetLmotelCollectorLoadBalanced(LmotelcollectorLoadBalanced *bool) {
	o.LmotelCollectorLoadBalanced = LmotelcollectorLoadBalanced
}

// WithForceUpdateFailedOverDevices adds the forceUpdateFailedOverDevices to the update collector by Id params
func (o *UpdateLmotelCollectorByIDParams) WithForceUpdateFailedOverDevices(forceUpdateFailedOverDevices *bool) *UpdateLmotelCollectorByIDParams {
	o.SetForceUpdateFailedOverDevices(forceUpdateFailedOverDevices)
	return o
}

// SetForceUpdateFailedOverDevices adds the forceUpdateFailedOverDevices to the update collector by Id params
func (o *UpdateLmotelCollectorByIDParams) SetForceUpdateFailedOverDevices(forceUpdateFailedOverDevices *bool) {
	o.ForceUpdateFailedOverDevices = forceUpdateFailedOverDevices
}

// WithID adds the id to the update collector by Id params
func (o *UpdateLmotelCollectorByIDParams) WithID(id int32) *UpdateLmotelCollectorByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update collector by Id params
func (o *UpdateLmotelCollectorByIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateLmotelCollectorByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.LmotelCollectorLoadBalanced != nil {

		// query param collectorLoadBalanced
		var qrLmotelCollectorLoadBalanced bool
		if o.LmotelCollectorLoadBalanced != nil {
			qrLmotelCollectorLoadBalanced = *o.LmotelCollectorLoadBalanced
		}
		qLmotelCollectorLoadBalanced := swag.FormatBool(qrLmotelCollectorLoadBalanced)
		if qLmotelCollectorLoadBalanced != "" {
			if err := r.SetQueryParam("LmotelcollectorLoadBalanced", qLmotelCollectorLoadBalanced); err != nil {
				return err
			}
		}

	}

	if o.ForceUpdateFailedOverDevices != nil {

		// query param forceUpdateFailedOverDevices
		var qrForceUpdateFailedOverDevices bool
		if o.ForceUpdateFailedOverDevices != nil {
			qrForceUpdateFailedOverDevices = *o.ForceUpdateFailedOverDevices
		}
		qForceUpdateFailedOverDevices := swag.FormatBool(qrForceUpdateFailedOverDevices)
		if qForceUpdateFailedOverDevices != "" {
			if err := r.SetQueryParam("forceUpdateFailedOverDevices", qForceUpdateFailedOverDevices); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
